# -*- coding: utf-8 -*-
"""semantic-segment-anything.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HZdH_8KdxHsIbIprroT4ElBc26K1DgSh
"""

pip install replicate

pip install pycocotools

pip install pixellib

pip install torch


import replicate
import os
import pixellib

from io import BytesIO
import requests
import fileinput

api = replicate.Client(api_token="r8_W8hm2222o0t9vBr3qfMUL5ZRwNRMYBM43CQv1")

image_path = input("Enter the path to the local image file: ")

with open(image_path, "rb") as file:
    image_data = BytesIO(file.read())

output = api.run(
    "cjwbw/semantic-segment-anything:b2691db53f2d96add0051a4a98e7a3861bd21bf5972031119d344d956d2f8256",
    input={
        "image": image_data
    }
)

print(output)

from pixellib.torchbackend.instance import instanceSegmentation

ins = instanceSegmentation()
ins.load_model("/content/pointrend_resnet50.pkl")
ins.segmentImage(image_path, output_image_name = "newimage.jpg")
